import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./components/globals.css";

const geistSans = Geist({
  variable: "--fonA-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import ParticleBackground from "./components/ParticleBackground";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ParticleBackground />
        {children}
      </body>
    </html>
  );
}
